language: csharp
mono: none
dist: xenial
dotnet: 5.0.100
install:
  - dotnet restore kankicache
  - dotnet restore kankicache.tests
script:
  - dotnet build kankicache
  - dotnet build kankicache.tests
  - dotnet test kankicache.tests/kankicache.tests.csproj
  - dotnet test kankicache.tests/kankicache.tests.csproj /p:CollectCoverage=true